name: Build Taxonomy SVG and replace Notion block (image)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Zurich

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install biopython matplotlib notion-client

      - name: Run builder + Notion replace
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          NOTION_BLOCK_ID: ${{ secrets.NOTION_BLOCK_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_BACK: ${{ secrets.COMMIT_BACK }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
          IMAGE_URL: ${{ secrets.IMAGE_URL }}   # optional override
        run: |
          python update_tree_svg_block_replace.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: phylo-tree-data
          path: data
